package com.extera.plugins.exitfy;

// Generated by tools/generate_provider_catalog.py. Input fingerprint: 3d828569968fbe868890f7c9f128df4bed144540701022ced3f128037699e5df
final class CatalogMaterialA {
    private static final long[][] VALUES = {
            {
                    0x132203e07b333368L, 0x640fa7aa9ee27eb2L,
                    0xab67b97cff6f8876L, 0x6bfb65bb13cb32a1L,
            },
            {
                    0x33eb559d91634788L, 0xf06b68eff12edb82L,
                    0x903c07ccf334120fL, 0x65f6ead9ec9b45b7L,
            },
    };

    private CatalogMaterialA() {
    }

    static byte[] value(int index) {
        return expand(VALUES[index]);
    }

    private static byte[] expand(long[] values) {
        byte[] output = new byte[values.length * 8];
        int offset = 0;
        for (long value : values) {
            for (int shift = 56; shift >= 0; shift -= 8) {
                output[offset++] = (byte) (value >>> shift);
            }
        }
        return output;
    }
}
