package com.extera.plugins.exitfy;

// Generated by tools/generate_provider_catalog.py. Input fingerprint: 3d828569968fbe868890f7c9f128df4bed144540701022ced3f128037699e5df
final class CatalogMaterialB {
    private static final long[][] VALUES = {
            {
                    0xf44067aee6b89ff4L, 0x4a97d81873bc1ab4L,
                    0x3402f034e38a18c0L, 0x5193c921c3fd38c3L,
            },
            {
                    0xd13a42cdb8c4e3fdL, 0xb1727cbfa11dcd0fL,
                    0xb6d9a8b5bad380c0L, 0x8081cb586637f76fL,
            },
    };

    private CatalogMaterialB() {
    }

    static byte[] value(int index) {
        return expand(VALUES[index]);
    }

    private static byte[] expand(long[] values) {
        byte[] output = new byte[values.length * 8];
        int offset = 0;
        for (long value : values) {
            for (int shift = 56; shift >= 0; shift -= 8) {
                output[offset++] = (byte) (value >>> shift);
            }
        }
        return output;
    }
}
