package com.extera.plugins.exitfy;

// Generated by tools/generate_provider_catalog.py. Input fingerprint: 61c4971b230d45b237a4716e0a0907b36d0e99b395a4027232744b852b153916
final class CatalogMaterialB {
    private static final long[][] VALUES = {
            {
                    0x94c1448908a8bd7fL, 0x992afcb3e173f9b0L,
                    0xbdaf06cdb706419dL, 0xe5a673930eabbe9aL,
            },
            {
                    0x3bc3773a8f32149eL, 0x7ed02e5206af862bL,
                    0xacf8230249cbe909L, 0x4c80a0c5f7d3d8a9L,
            },
            {
                    0x0eb384791cc9e91cL, 0x37d0dace67322ed8L,
                    0xea7eccc0045c72d1L, 0xf3071549c2cf7517L,
            },
    };

    private CatalogMaterialB() {
    }

    static byte[] value(int index) {
        return expand(VALUES[index]);
    }

    private static byte[] expand(long[] values) {
        byte[] output = new byte[values.length * 8];
        int offset = 0;
        for (long value : values) {
            for (int shift = 56; shift >= 0; shift -= 8) {
                output[offset++] = (byte) (value >>> shift);
            }
        }
        return output;
    }
}
