package com.extera.plugins.exitfy;

// Generated by tools/generate_provider_catalog.py. Input fingerprint: 61c4971b230d45b237a4716e0a0907b36d0e99b395a4027232744b852b153916
final class CatalogMaterialA {
    private static final long[][] VALUES = {
            {
                    0xa38be33c91aa4f14L, 0x0c4230ef7d2b3b41L,
                    0x46f1f890813d28eaL, 0xa3df1feddea9a4f7L,
            },
            {
                    0xd94443431b7f7b98L, 0xad8f6530f5651841L,
                    0x4fff23333dd5bad9L, 0xc9514607f1308f1bL,
            },
            {
                    0x65b55b37fe355fbcL, 0xc8e0bf2813d5a7a1L,
                    0xf1156493da0192feL, 0xb08c9def2a13673eL,
            },
    };

    private CatalogMaterialA() {
    }

    static byte[] value(int index) {
        return expand(VALUES[index]);
    }

    private static byte[] expand(long[] values) {
        byte[] output = new byte[values.length * 8];
        int offset = 0;
        for (long value : values) {
            for (int shift = 56; shift >= 0; shift -= 8) {
                output[offset++] = (byte) (value >>> shift);
            }
        }
        return output;
    }
}
