package com.extera.plugins.exitfy;

// Generated by tools/generate_provider_catalog.py. Input fingerprint: 3d828569968fbe868890f7c9f128df4bed144540701022ced3f128037699e5df
final class ProviderCatalogData {
    private static final boolean[] ENABLED = {true, true};
    private static final int[][] NONCES = {
            {
                    156, 162, 89, 239, 253, 30, 37, 174, 43, 153, 56, 176,
                    14, 75, 109, 155,
            },
            {
                    212, 140, 231, 29, 16, 183, 132, 39, 139, 195, 11, 143,
                    210, 136, 82, 148,
            },
    };
    private static final int[][] PAYLOADS = {
            {
                    60, 120, 236, 12, 57, 23, 164, 24, 242, 205, 1, 50,
                    116, 222, 142, 33, 33, 186, 11, 143, 12, 112, 129, 0,
                    163, 87, 16, 13, 13, 156, 188, 159, 222, 114, 99, 251,
                    132, 232, 73, 120, 19, 75, 30, 138, 84, 170, 232,
            },
            {
                    160, 114, 200, 35, 113, 65, 160, 77, 1, 133, 228, 13,
                    128, 252, 107, 227, 225, 140, 43, 83, 155, 107, 193, 96,
                    186, 214, 44, 145, 121, 123, 172, 245, 204, 102, 166, 181,
                    56, 120, 136, 201, 38, 218, 224, 76, 73, 241, 246, 129,
                    253, 137, 251,
            },
    };
    private static final int[][] TAGS = {
            {
                    10, 245, 219, 229, 163, 157, 118, 130, 232, 43, 47, 203,
                    228, 112, 52, 5,
            },
            {
                    224, 49, 12, 40, 112, 237, 137, 185, 136, 37, 115, 249,
                    14, 230, 129, 27,
            },
    };

    private ProviderCatalogData() {
    }

    static int size() {
        return ENABLED.length;
    }

    static boolean enabled(int index) {
        return ENABLED[index];
    }

    static byte[] nonce(int index) {
        return bytes(NONCES[index]);
    }

    static byte[] payload(int index) {
        return bytes(PAYLOADS[index]);
    }

    static byte[] tag(int index) {
        return bytes(TAGS[index]);
    }

    private static byte[] bytes(int[] values) {
        byte[] output = new byte[values.length];
        for (int index = 0; index < values.length; index++) output[index] = (byte) values[index];
        return output;
    }
}
