package com.extera.plugins.exitfy;

// Generated by tools/generate_provider_catalog.py. Input fingerprint: 61c4971b230d45b237a4716e0a0907b36d0e99b395a4027232744b852b153916
final class ProviderCatalogData {
    private static final boolean[] ENABLED = {true, true, true};
    private static final int[][] NONCES = {
            {
                    140, 31, 204, 167, 88, 175, 131, 104, 163, 204, 239, 0,
                    65, 36, 11, 124,
            },
            {
                    159, 21, 190, 190, 99, 254, 23, 207, 150, 179, 128, 214,
                    163, 180, 182, 207,
            },
            {
                    191, 69, 58, 111, 57, 232, 117, 3, 48, 59, 26, 168,
                    125, 13, 107, 102,
            },
    };
    private static final int[][] PAYLOADS = {
            {
                    235, 93, 92, 171, 102, 88, 229, 135, 110, 124, 202, 221,
                    153, 198, 142, 65, 224, 228, 238, 218, 32, 236, 176, 32,
                    195, 99, 131, 165, 164, 164, 164, 22, 87, 221, 5, 148,
                    211, 36, 193, 139, 118, 46, 35, 157, 120, 174, 97, 250,
                    98, 229, 156,
            },
            {
                    230, 143, 139, 153, 238, 159, 19, 117, 227, 142, 178, 7,
                    141, 42, 148, 178, 103, 18, 122, 204, 208, 236, 30, 220,
                    161, 167, 53, 107, 48, 211, 39, 252, 173, 96, 150, 133,
                    169, 206, 186, 36, 86, 207, 131, 190, 141, 119, 190,
            },
            {
                    209, 252, 175, 19, 242, 52, 81, 147, 251, 127, 14, 104,
                    12, 110, 56, 7, 118, 247, 116, 235, 59, 87, 121, 21,
                    241, 227, 124, 31, 213, 151, 244,
            },
    };
    private static final int[][] TAGS = {
            {
                    201, 155, 86, 31, 181, 211, 206, 4, 3, 205, 233, 70,
                    32, 208, 68, 17,
            },
            {
                    7, 231, 129, 58, 236, 156, 67, 40, 107, 116, 3, 206,
                    141, 57, 118, 143,
            },
            {
                    55, 86, 192, 112, 83, 132, 59, 196, 231, 131, 11, 49,
                    177, 188, 193, 154,
            },
    };

    private ProviderCatalogData() {
    }

    static int size() {
        return ENABLED.length;
    }

    static boolean enabled(int index) {
        return ENABLED[index];
    }

    static byte[] nonce(int index) {
        return bytes(NONCES[index]);
    }

    static byte[] payload(int index) {
        return bytes(PAYLOADS[index]);
    }

    static byte[] tag(int index) {
        return bytes(TAGS[index]);
    }

    private static byte[] bytes(int[] values) {
        byte[] output = new byte[values.length];
        for (int index = 0; index < values.length; index++) output[index] = (byte) values[index];
        return output;
    }
}
